[package]
name = "day08"
version = "0.1.0"
authors = ["Rafał Cieślak <ravicious@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
linked_hash_set = "0.1.4"
